name: Renovaciones Licencias

on:
  schedule:
    - cron: "0 13 * * *" # 8am Colombia (UTC-5)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo credenciales.json desde secrets
        run: echo "${{ secrets.CREDENTIALS_JSON }}" > credenciales.json

      - name: Ejecutar script
        env:
          EMAIL_ORIGEN: ${{ secrets.EMAIL_ORIGEN }}
          EMAIL_CLAVE: ${{ secrets.EMAIL_CLAVE }}
        run: python renovations.py
