# .github/workflows/renovaciones.yml
name: Renovaciones Licencias

on:
  schedule:
    - cron: "0 13 * * *"  # 8am Colombia (UTC-5)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install pandas
      - name: Run script
        run: python renovations.py
